use_frameworks!

platform :ios, '14.0'

target 'HYAsyncDisplayKit_Example' do
  pod 'HYAsyncDisplayKit', :path => '../'

  target 'HYAsyncDisplayKit_Tests' do
    inherit! :search_paths

    
  end
end
