use_frameworks!

platform :ios, '14.0'

target 'HYAsyncDisplayKit_Example' do
  pod 'HYAsyncDisplayKit', :path => '../'

#  pod 'GDKAsyncDisplayKit', '0.0.5'


  target 'HYAsyncDisplayKit_Tests' do
    inherit! :search_paths

    
  end
end
